## Challenge - Joining on multiple tables
#Write SQL queries to perform the following tasks using the Sakila database:
#1. List the number of films per category.
#2. Retrieve the store ID, city, and country for each store.
#3.  Calculate the total revenue generated by each store in dollars.
#4.  Determine the average running time of films for each category.

use sakila;
show tables;

#1. List the number of films per category.
SELECT 
    c.name AS category_name,
    COUNT(f.film_id) AS number_of_films
FROM 
    film f
JOIN 
    film_category fc ON f.film_id = fc.film_id
JOIN 
    category c ON fc.category_id = c.category_id
GROUP BY 
    c.name
ORDER BY 
    number_of_films DESC;
    
#2. Retrieve the store ID, city, and country for each store.    
SELECT 
    s.store_id,
    ci.city,
    co.country
FROM 
    store s
JOIN 
    address a ON s.address_id = a.address_id
JOIN 
    city ci ON a.city_id = ci.city_id
JOIN 
    country co ON ci.country_id = co.country_id;
    
#3.  Calculate the total revenue generated by each store in dollars.    
SELECT store.store_id, SUM(payment.amount) AS total_revenue
FROM store
JOIN staff ON store.store_id = staff.store_id
JOIN payment ON staff.staff_id = payment.staff_id
GROUP BY store.store_id;
    
    
#4.  Determine the average running time of films for each category.    
SELECT 
    c.name AS category_name,
    ROUND(AVG(f.length), 2) AS average_running_time
FROM 
    film f
JOIN 
    film_category fc ON f.film_id = fc.film_id
JOIN 
    category c ON fc.category_id = c.category_id
GROUP BY 
    c.name
ORDER BY 
    average_running_time DESC;